name: Automated Tests

on: pull_request

jobs:
  test:
    name: Tests Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - run: pnpm install

      - run: pnpm run test
