name: Automated Tests

on: pull_request

jobs:
  test:
    name: Tests Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: lts/iron

      - run: npm ci

      - run: npm test
